In [1]:
import numpy as np
import pandas as pd
from sklearn.externals import joblib
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import json
import re
import os

### load dict

In [3]:
dt_pt = open('all.dict', 'r')
vocab = json.load(dt_pt)
dt_pt.close()

In [7]:
print(len(vocab))
print(vocab['英语'])

76192
50769


In [11]:
def id2tk(vb):
    dict_ = {}
    for i in vb.items():
        dict_[i[1]]=i[0]
    return dict_

id_to_tk = id2tk(vocab)
len(id_to_tk)

76192

In [13]:
lda = joblib.load('lda.pkl')

F:\Anaconda3\lib\site-packages\sklearn\base.py:312: UserWarning: Trying to unpickle estimator LatentDirichletAllocation from version 0.18.1 when using version 0.19.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [19]:
topic_token = lda.components_

In [20]:
topic_token.shape

(100, 76192)

In [25]:
X_test_doc_topic = np.load('X_test_tps.npy')

In [26]:
X_test_doc_topic.shape

(87026, 100)

### ============topic and token matrix==============================

In [56]:
exp0=topic_token[0]
exp0

array([ 0.01,  0.01,  0.01, ...,  0.01,  0.01,  0.01])

In [61]:
print(exp0.min())
print(exp0.max())

0.01
8633.71927056


In [51]:
main_id = exp0.argsort()[-50:]

In [52]:
main_tk = []
for i in main_id:
    main_tk.append(id_to_tk[i])
print(main_tk)

['起舞', '蝴', '哲理', '里面', '用心', '频发', '洒', '巡', '感染', '啲', '悉', '不由', '数人', '匀', '茫茫', '歌曲', '晴', '反思', '洞庭', '灰', '厉害', '困', '谚语', '预习', '平凡', '翠', '隐', '值得', '歌声', '泪', '下水', '无限', '献', '烈士', '山水', '玄', '永', '横', '百万', '喜爱', '存', '无数', '客', '强烈', '纬线', '事迹', '未', '英雄', '诗句', '情']


In [53]:
exp=topic_token[52]
main_id = exp.argsort()[-50:]
main_tk = []
for i in main_id:
    main_tk.append(id_to_tk[i])
print(main_tk)

['水里', '学时', '几条', '黑暗', '继', '初年', '四面', '果实', '物种', '的确', '仔', '单一', '肃', '而有', '操', '新鲜', '兴趣小组', '感兴趣', '尾巴', '一开', '感兴', '登上', '西西', '辉', '盐', '比亚', '博物馆', '安新', '群体', '一多', '救', '整个', '博物', '高大', '树木', '这条', '唱', '分类', '新区', '标题', '巨', '节选', '兴趣', '感悟', '除了', '哪里', '形象', '陈', '变', '种']


In [54]:
exp=topic_token[88]
main_id = exp.argsort()[-50:]
main_tk = []
for i in main_id:
    main_tk.append(id_to_tk[i])
print(main_tk)

['国情', '卫生', '中指', '参与', '根本', '同体', '三次', '如下', '振兴', '垃圾', '人均', '分配', '运用', '标准', '主题', '搜集', '九年', '始终', '体现', '反映', '服务', '为主', '提出', '关注', '兴', '开展', '九大', '大报', '指出', '民生', '十九', '乡村', '居民', '实践', '公共', '必须', '矛盾', '解决', '群众', '实施', '家庭', '农民', '调查', '共同', '存在', '农村', '战略', '报告', '工作', '探究']


In [55]:
exp=topic_token[99]
main_id = exp.argsort()[-50:]
main_tk = []
for i in main_id:
    main_tk.append(id_to_tk[i])
print(main_tk)

['义民', '素有', '自治制', '整治', '议政', '主权', '假期', '选举权', '天文', '一项', '维吾尔', '各项', '宁夏', '得益于', '口口', '浮', '民族区域', '基本', '政治权利', '旅游业', '益于', '游业', '景点', '政治经济', '得益', '政治权', '景区', '群众', '观看', '理性', '主政', '票', '当家作主', '治权', '作主', '民众', '基层', '食物', '当家', '切', '意志', '当地', '自治区', '选举', '自治', '属于', '民主', '制度', '旅游', '政治']


In [66]:
def print_tp_main_tks(id_):
    exp = topic_token[id_]
    main_id = exp.argsort()[-50:]
    main_tk = []
    for i in main_id:
        main_tk.append(id_to_tk[i])
    print(main_tk)

### ==================doc & topic matrix=============================

In [73]:
exp=X_test_doc_topic[0]
exp

array([  2.70270270e-04,   2.70270270e-04,   2.70270270e-04,
         2.70270270e-04,   2.70270270e-04,   2.70270270e-04,
         2.70270270e-04,   2.70270270e-04,   2.70270270e-04,
         2.70270270e-04,   2.70270270e-04,   2.70270270e-04,
         2.70270270e-04,   2.91284766e-02,   2.70270270e-04,
         2.70270270e-04,   3.09763748e-02,   2.70270270e-04,
         2.70270270e-04,   2.70270270e-04,   2.70270270e-04,
         1.01739456e-01,   2.70270270e-04,   2.70270270e-04,
         2.70270270e-04,   2.70270270e-04,   2.70270270e-04,
         2.70270270e-04,   2.70270270e-04,   2.70270270e-04,
         2.70270270e-04,   2.70270270e-04,   2.70270270e-04,
         2.70270270e-04,   2.70270270e-04,   2.70270270e-04,
         2.70270270e-04,   2.70270270e-04,   2.70270270e-04,
         2.70270270e-04,   4.40609801e-01,   2.70270270e-04,
         2.70270270e-04,   2.70270270e-04,   2.70270270e-04,
         2.70270270e-04,   2.70270270e-04,   2.70270270e-04,
         1.02763253e-01,

In [63]:
print(exp.min())
print(exp.max())

0.00027027027027
0.440609801406


In [74]:
main_tp = exp.argsort()[-4:]
main_tp

array([73, 21, 48, 40], dtype=int64)

In [75]:
for tp in main_tp:
    print_tp_main_tks(tp)

['北朝', '过度', '下图', '消极', '不稳', '东南部', '深远', '大影', '南风', '读图', '北向', '广阔', '拍摄', '处在', '依赖', '南', '荷兰', '东', '陕西', '纬度', '缺乏', '很大', '反映', '崛起', '中央集权', '向东', '集权', '海外', '接', '省区', '照片', '学期', '手机', '东南', '居', '结构', '走向', '支持', '西南', '西', '南方', '商业', '范围', '说法', '西北', '北方', '东北', '产生', '方向', '影响']
['推动', '销售', '政策', '成本', '大型', '高速', '质量', '财政', '促进', '下降', '落后', '迅速', '投资', '电子', '达到', '需求', '强大', '结构', '人才', '竞争', '国内', '数据', '全国', '亿元', '价格', '模式', '互联网', '增加', '经营', '消费', '联网', '劳动', '互联', '持续', '收入', '制造', '服务', '产品', '动力', '规模', '全球', '市场', '提高', '水平', '产业', '生产', '增长', '技术', '企业', '经济']
['山顶', '某区', '常见', '集体生活', '厉', '绘制', '是否', '读图', '村庄', '局部', '暑假', '距离', '尼', '个性', '比例尺', '实地', '观点', '某地', '庄', '班集体', '图表', '成员', '角色', '中所', '图图', '图示', '考虑', '收', '体育', '名言', '同意', '游客', '等高线', '高线', '利益', '村', '规律', '比例', '司', '对此', '下图', '回', '个人', '太', '一位', '示意图', '意图', '有人', '示意', '集体']
['起伏', '东部', '珠', '依次', '穿过', '地处', '东半', '湾', '南美洲', '南半球', '东北', '南美', '南部', '海陆', '西半球', '低', '沿'

### example2

In [76]:
exp=X_test_doc_topic[12]
main_tp = exp.argsort()[-4:]
for tp in main_tp:
    print_tp_main_tks(tp)

['花朵', '挂', '树林', '后面', '并用', '一动', '眼前', '尾', '查阅', '舍', '之前', '敢', '第二天', '幅', '正在', '原文', '像是', '星星', '前面', '二天', '小孩', '干什么', '折', '绝', '杀', '选自', '不见', '小心', '礼', '艰苦', '志', '空中', '不动', '字词', '天空', '突然', '象', '好像', '什', '积累', '故', '跑', '形容', '想到', '恰当', '横线', '成语', '完整', '补充', '词语']
['只要', '正面', '涛', '岭', '拥有', '化生', '生命', '排', '正常', '管', '挫折', '渴望', '研', '彩', '矛盾', '纳', '生理', '课内', '得分', '危险', '辨析题', '不知', '注意', '掌握', '人生', '观点', '片', '选文', '处理', '办', '有时', '青春期', '快', '身体', '辨析', '家乡', '仅', '心理', '刘', '位', '白', '实', '介绍', '合', '不得', '啊', '选', '爸爸', '知道', '青春']
['定会', '批评', '白杨', '拼', '丢', '学到', '同桌', '文说', '难忘', '不怕', '即将', '习作', '走到', '具体', '愿意', '明明', '题写', '上课', '微笑', '课堂', '六年', '马上', '为题', '松', '就要', '不管', '身边', '小学', '声音', '真的', '图书', '别的', '一处', '倒', '小学生', '童年', '认真', '同学们', '仿照', '有些', '心里', '想一想', '事情', '上面', '语', '七', '写下', '吧', '下来', '老师']
['后来', '女', '过来', '以后', '家里', '一直', '放在', '回到', '奶奶', '听到', '而是', '看见', '进', '只是', '总是', '这么', '见', '笑', '来说', '过去', '拿', '住', '似

### example3

In [77]:
exp=X_test_doc_topic[17]
main_tp = exp.argsort()[-4:]
for tp in main_tp:
    print_tp_main_tks(tp)

['简明', '医学', '所用', '创意', '贺', '那种', '山河', '撰写', '环节', '固定', '此外', '较为', '有用', '步骤', '植', '一则', '金属', '宇宙', '小事', '投入', '研发', '反问句', '月球', '大众', '行社', '轴', '教授', '率', '三条', '反问', '改成', '一两', '问句', '效果', '广告', '唐代', '名字', '吸引', '广泛', '简单', '然而', '而且', '生物', '速度', '交', '重点', '取', '突出', '设计', '非常']
['捧', '册', '旭', '朗', '饿', '埋', '库', '一丝', '叼', '悄悄', '路口', '前人', '薄', '恶', '尘', '索', '序', '夫人', '百年', '翠鸟', '先查', '查字典', '感想', '音节', '写字', '翻', '峰', '查字法', '音序', '水面', '尸', '部', '病', '字典', '升', '部首', '双', '程', '从中', '查字', '分钟', '戈', '右', '除', '果', '查', '是因为', '练习', '解释', '意思']
['合题', '购物', '购买', '身份', '监管', '专题', '单项', '电话', '出席', '网站', '假', '店', '金砖', '紧扣', '支付', '损失', '访问', '剑', '版', '日出', '均', '匹', '家中', '题意', '工人', '上述', '所学', '打击', '几乎', '试题', '期间', '中考', '案件', '办公', '走进', '试卷', '大题', '万元', '件', '网', '考试', '条', '六', '俄罗斯', '非', '选择题', '参加', '罗斯', '网络', '小题']
['获取', '警示', '导致', '意识', '现场', '属于', '人民币', '引发', '判决', '公安机关', '违反', '非法', '侵犯', '网民', '一致', '违法行为', '发布', '评', '拘留', '列车', '小强', '被告

In [78]:
exp=X_test_doc_topic[26]
main_tp = exp.argsort()[-4:]
for tp in main_tp:
    print_tp_main_tks(tp)

['海军', '朝', '重心', '两国', '宣言', '鸦片', '中日', '法国', '势力', '世界大战', '斗争', '这场', '危机', '俄国', '签订', '义国', '近代', '两次', '战役', '抗战', '爆发', '军事', '胜利', '抗日', '殖民', '大战', '朝鲜', '条约', '南京', '最早', '侵略', '第二次', '第一次', '苏联', '军', '德国', '解放', '帝国', '世纪', '国主', '二次', '资本主义', '新疆', '和平', '本主', '资本', '日本', '主义', '英国', '战争']
['护宪', '全体', '完整', '映出', '以上', '行宪', '权力', '颁布', '史实', '本法', '民', '依据', '权威', '中华人民共和国宪法', '民主', '一切', '法', '法制', '两幅', '国歌', '宪', '所学', '宣誓', '通顺', '规定', '制定', '修改', '制度', '法律', '整体', '表述', '全国人民代表大会', '反映', '语句', '体现', '会议', '根本', '人民代表大会', '人民代表', '代表大会', '中华人民共和国', '大会', '人民共和国', '中华人民', '共和国', '图片', '华人', '中华', '共和', '宪法']
['马六甲海峡', '包产', '新航', '往来', '航路', '地名', '外包', '马六甲', '六甲', '陶', '频繁', '保留', '解析', '介', '空前', '可分', '交易', '东亚', '经济带', '航海', '地主', '国王', '多个', '国一', '一分', '每题', '小数', '连续', '类', '郑和', '阿拉伯', '拉伯', '印度洋', '地区', '西亚', '阿拉', '一路', '木', '寸', '海上', '根', '东南亚', '分为', '丝绸之路', '东南', '丝绸', '南亚', '之路', '土地', '印度']
['市政', '干部', '合法', '执行', '难以', '维护', '高中', '效率', '必须', '合法权'

76303392758	9	A使各国产品单一A有力推进了世界经济全球化N读图N某大洲示意图关于该大洲的叙述正确的是A人口主要分布于东部东南部和南部A地势中部低四周高A全部位于东半球北半球

70883815525	1	N阅读下面的文字回答问题父与子在日本一位父亲带着N岁的儿子郊游父亲钓鱼儿子在一旁玩耍在离湖边不远处有一个很深的大坑孩子好奇自己偷偷摸索着下到坑里玩了一阵后他发现大坑离地面高下来容易上去难于是他不得不求助正在钓鱼的父亲爸爸爸爸帮帮我找上不去了但他没有到A应其实此时此刻他知道他的父亲正在距离他不远的地方钓鱼他没有想到父亲会对其助置之不理于是他的第一个反应就是愤怒他开始直呼父亲大人的名字并称之为八牙路混蛋他的父亲还是置之不理这时天渐渐地黑下来出于恐惧和无助他的第二个反应是哭泣又哭又喊足以令亲的揪心结果得到的反应还是沉默之后他不得不自己想办法了他在坑里转来转去讲我可以上去的地方终于他发现在坑的另一面有几棵可以用于攀缘的小树他艰难地上来此时此刻他发现父亲还在那里叼着烟卷悠闲地一动不动地钓着他的鱼令人意想的是这个顽童没有抱怨更没有愤怒而是径直走到父亲身边自豪地对父亲说老爸自己上来的

68599295707	7	N小强所在社会实践小组最近非常关注双N消费他们通过体验发现双N期间先涨价后降价虚构原价随意标注价格的情况较为突出对此他们可以向消费者协会反映不在双N购物向工商管理部门举报对商家人肉搜索ANANA

68923595151	8	N自N年起<英国国王不再行使议会立去否决但国王仍可通过赏赐官金王A控制议会据统计N世纪初英国有N名议会下院义员从国王府那里得到职位年金以后多年此类议员有增无咸这些义员对国王感惟命是从被称为宫廷党上述史实反映出英国A议会拥有立法否决权A脚宪制度同虚设A王权衰一各过程的曲折A立宪体制吓王权的扩长

In [79]:
exp=X_test_doc_topic[41]
main_tp = exp.argsort()[-4:]
for tp in main_tp:
    print_tp_main_tks(tp)

['四年级', '恨', '蜜蜂', '一番', '货', '训', '不成', '猴子', '付', '方程', '寓言', '标出', '委', '盘', '显', '兀', '劝', '乏', '文解', '凶', '构成', '坚强', '皮', '做好', '练', '四年', '底', '比喻句', '三角形', '已知', '三角', '角形', '以及', '数学', '展开', '发出', '鸟', '告诉', '罗', '系上', '上下文', '下文', '边', '比喻', '答', '上下', '气', '想象', '求', '表示']
['水里', '学时', '几条', '黑暗', '继', '初年', '四面', '果实', '物种', '的确', '仔', '单一', '肃', '而有', '操', '新鲜', '兴趣小组', '感兴趣', '尾巴', '一开', '感兴', '登上', '西西', '辉', '盐', '比亚', '博物馆', '安新', '群体', '一多', '救', '整个', '博物', '高大', '树木', '这条', '唱', '分类', '新区', '标题', '巨', '节选', '兴趣', '感悟', '除了', '哪里', '形象', '陈', '变', '种']
['天天', '手指', '送给', '明白', '事情', '秘密', '怀', '杰', '花园', '恩', '疑', '园里', '渐渐', '解答', '想想', '安静', '染', '日记', '飞', '医', '室', '寻', '心中', '地下', '想起', '不了', '看着', '谷', '色彩', '日子', '今天', '公园', '读一读', '常常', '竹', '园', '仿', '影', '放', '往', '一件', '道理', '玉', '活', '鱼', '别人', '真', '事', '看到', '花']
['离', '摘', '扣', '透明', '肥', '田野', '乔', '亏', '钢', '梨', '竟然', '勤', '夜晚', '中括号', '高高', '矢', '一群', '够', '留学', '威', '高峰', '小草', '明天', '找出', '肉', '鲜花

72318571265	1	N照样子写一写鱼鱼昆鲫陈鸟鹏鹊月股膀

In [80]:
exp=X_test_doc_topic[95]
main_tp = exp.argsort()[-4:]
for tp in main_tp:
    print_tp_main_tks(tp)

['斯特', '升起', '五年级', '一夜', '艾', '掉', '秦始皇', '私有', '碧', '奴隶', '诸侯', '白云', '名句', '封建社会', '山上', '王国', '人教版', '始皇', '害怕', '铺', '公元前', '墙', '羽', '曹', '慢', '贵族', '深深', '等于', '头上', '战国', '国中', '背', '用于', '上升', '只能', '公元', '笑', '大地', '毛', '叶', '精', '早', '确', '穿', '不到', '感动', '大小', '五年', '绿色', '曾']
['最多', '部门', '海岸', '葡萄', '港口', '中分', '纺织', '农产品', '不利', '手工业', '要是', '农产', '工厂', '配', '矿产资源', '工业化', '称为', '出口', '形成', '由于', '有利', '沿岸', '手工', '布局', '世纪', '斯', '京', '为主', '石油', '工业区', '产品', '品', '矿产', '优势', '集中', '运输', '分布', '发达', '丰富', '年代', '经济', '交通', '业', '因素', '农业', '日本', '条件', '铁路', '资源', '工业']
['该城', '古老', '遭受', '城市群', '内地', '优先', '两部', '饮食', '早上', '住宅', '西安', '珠江三角洲', '计算机', '珠江三角', '算机', '整理', '城市化', '尚', '长江三角洲', '计算', '长江三角', '软件', '野', '燃', '深圳', '大城市', '大城', '专业', '原料', '伟', '长沙', '珠江', '沿海', '长江', '素质', '便利', '晚上', '往往', '交通', '冲突', '现实', '香', '三角洲', '广州', '头', '三角', '描述', '市', '红', '城市']
['学说', '坡', '三年', '确保', '一项', '保险', '两年', '信心', '节约', '提', '我省', '友谊', '贫困人口', '实现', '物品', '国文', '启发

66462174618	8	N联系材料二及所学知识谈谈你对城市化与工业化互为因果而螺旋式上升的关系的理解N分